<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-area-chart"></i> <span class="icon-name"> area-chart</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-bar-chart"></i> <span class="icon-name"> bar-chart</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-bar-chart-o"></i> <span class="icon-name"> bar-chart-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-line-chart"></i> <span class="icon-name"> line-chart</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-pie-chart"></i> <span class="icon-name"> pie-chart</span></a></li>
</ul>