<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-check-square"></i> <span class="icon-name"> check-square</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-check-square-o"></i> <span class="icon-name"> check-square-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-circle"></i> <span class="icon-name"> circle</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-circle-o"></i> <span class="icon-name"> circle-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-dot-circle-o"></i> <span class="icon-name"> dot-circle-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-minus-square"></i> <span class="icon-name"> minus-square</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-minus-square-o"></i> <span class="icon-name"> minus-square-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-plus-square"></i> <span class="icon-name"> plus-square</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-plus-square-o"></i> <span class="icon-name"> plus-square-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-square"></i> <span class="icon-name"> square</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-square-o"></i> <span class="icon-name"> square-o</span></a></li>
</ul>