<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-file"></i> <span class="icon-name"> file</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-archive-o"></i> <span class="icon-name"> file-archive-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-audio-o"></i> <span class="icon-name"> file-audio-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-code-o"></i> <span class="icon-name"> file-code-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-excel-o"></i> <span class="icon-name"> file-excel-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-image-o"></i> <span class="icon-name"> file-image-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-movie-o"></i> <span class="icon-name"> file-movie-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-o"></i> <span class="icon-name"> file-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-pdf-o"></i> <span class="icon-name"> file-pdf-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-photo-o"></i> <span class="icon-name"> file-photo-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-picture-o"></i> <span class="icon-name"> file-picture-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-powerpoint-o"></i> <span class="icon-name"> file-powerpoint-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-sound-o"></i> <span class="icon-name"> file-sound-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-text"></i> <span class="icon-name"> file-text</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-text-o"></i> <span class="icon-name"> file-text-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-video-o"></i> <span class="icon-name"> file-video-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-word-o"></i> <span class="icon-name"> file-word-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-file-zip-o"></i> <span class="icon-name"> file-zip-o</span></a></li>
</ul>