<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-ambulance"></i> <span class="icon-name"> ambulance</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-h-square"></i> <span class="icon-name"> h-square</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-heart"></i> <span class="icon-name"> heart</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-heart-o"></i> <span class="icon-name"> heart-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-heartbeat"></i> <span class="icon-name"> heartbeat</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-hospital-o"></i> <span class="icon-name"> hospital-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-medkit"></i> <span class="icon-name"> medkit</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-plus-square"></i> <span class="icon-name"> plus-square</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-stethoscope"></i> <span class="icon-name"> stethoscope</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-user-md"></i> <span class="icon-name"> user-md</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-wheelchair"></i> <span class="icon-name"> wheelchair</span></a></li>
</ul>