<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-ambulance"></i> <span class="icon-name"> ambulance</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-automobile"></i> <span class="icon-name"> automobile</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-bicycle"></i> <span class="icon-name"> bicycle</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-bus"></i> <span class="icon-name"> bus</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cab"></i> <span class="icon-name"> cab</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-car"></i> <span class="icon-name"> car</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-fighter-jet"></i> <span class="icon-name"> fighter-jet</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-motorcycle"></i> <span class="icon-name"> motorcycle</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-plane"></i> <span class="icon-name"> plane</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-rocket"></i> <span class="icon-name"> rocket</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-ship"></i> <span class="icon-name"> ship</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-space-shuttle"></i> <span class="icon-name"> space-shuttle</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-subway"></i> <span class="icon-name"> subway</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-taxi"></i> <span class="icon-name"> taxi</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-train"></i> <span class="icon-name"> train</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-truck"></i> <span class="icon-name"> truck</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-wheelchair"></i> <span class="icon-name"> wheelchair</span></a></li>
</ul>