<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-circle-o-notch fa-spin"></i> <span class="icon-name"> circle-o-notch</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cog fa-spin"></i> <span class="icon-name"> cog</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-gear fa-spin"></i> <span class="icon-name"> gear</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-refresh fa-spin"></i> <span class="icon-name"> refresh</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-spinner fa-spin"></i> <span class="icon-name"> spinner</span></a></li>
</ul>