<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-bitcoin"></i> <span class="icon-name"> bitcoin</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-btc"></i> <span class="icon-name"> btc</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cny"></i> <span class="icon-name"> cny</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-dollar"></i> <span class="icon-name"> dollar</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-eur"></i> <span class="icon-name"> eur</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-euro"></i> <span class="icon-name"> euro</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-gbp"></i> <span class="icon-name"> gbp</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-ils"></i> <span class="icon-name"> ils</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-inr"></i> <span class="icon-name"> inr</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-jpy"></i> <span class="icon-name"> jpy</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-krw"></i> <span class="icon-name"> krw</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-money"></i> <span class="icon-name"> money</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-rmb"></i> <span class="icon-name"> rmb</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-rouble"></i> <span class="icon-name"> rouble</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-rub"></i> <span class="icon-name"> rub</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-ruble"></i> <span class="icon-name"> ruble</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-rupee"></i> <span class="icon-name"> rupee</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-shekel"></i> <span class="icon-name"> shekel</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-sheqel"></i> <span class="icon-name"> sheqel</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-try"></i> <span class="icon-name"> try</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-turkish-lira"></i> <span class="icon-name"> turkish-lira</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-usd"></i> <span class="icon-name"> usd</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-won"></i> <span class="icon-name"> won</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-yen"></i> <span class="icon-name"> yen</span></a></li>
</ul>