<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-circle-thin"></i> <span class="icon-name"> circle-thin</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-genderless"></i> <span class="icon-name"> genderless</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-mars"></i> <span class="icon-name"> mars</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-mars-double"></i> <span class="icon-name"> mars-double</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-mars-stroke"></i> <span class="icon-name"> mars-stroke</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-mars-stroke-h"></i> <span class="icon-name"> mars-stroke-h</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-mars-stroke-v"></i> <span class="icon-name"> mars-stroke-v</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-mercury"></i> <span class="icon-name"> mercury</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-neuter"></i> <span class="icon-name"> neuter</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-transgender"></i> <span class="icon-name"> transgender</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-transgender-alt"></i> <span class="icon-name"> transgender-alt</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-venus"></i> <span class="icon-name"> venus</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-venus-double"></i> <span class="icon-name"> venus-double</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-venus-mars"></i> <span class="icon-name"> venus-mars</span></a></li>
</ul>