<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-arrows-alt"></i> <span class="icon-name"> arrows-alt</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-backward"></i> <span class="icon-name"> backward</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-compress"></i> <span class="icon-name"> compress</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-eject"></i> <span class="icon-name"> eject</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-expand"></i> <span class="icon-name"> expand</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-fast-backward"></i> <span class="icon-name"> fast-backward</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-fast-forward"></i> <span class="icon-name"> fast-forward</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-forward"></i> <span class="icon-name"> forward</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-pause"></i> <span class="icon-name"> pause</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-play"></i> <span class="icon-name"> play</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-play-circle"></i> <span class="icon-name"> play-circle</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-play-circle-o"></i> <span class="icon-name"> play-circle-o</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-step-backward"></i> <span class="icon-name"> step-backward</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-step-forward"></i> <span class="icon-name"> step-forward</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-stop"></i> <span class="icon-name"> stop</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-youtube-play"></i> <span class="icon-name"> youtube-play</span></a></li>
</ul>