<ul>
<li><a href='#' class='icon-sel'><i class="fa fa-cc-amex"></i> <span class="icon-name"> cc-amex</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cc-discover"></i> <span class="icon-name"> cc-discover</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cc-mastercard"></i> <span class="icon-name"> cc-mastercard</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cc-paypal"></i> <span class="icon-name"> cc-paypal</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cc-stripe"></i> <span class="icon-name"> cc-stripe</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-cc-visa"></i> <span class="icon-name"> cc-visa</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-credit-card"></i> <span class="icon-name"> credit-card</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-google-wallet"></i> <span class="icon-name"> google-wallet</span></a></li>
<li><a href='#' class='icon-sel'><i class="fa fa-paypal"></i> <span class="icon-name"> paypal</span></a></li>
</ul>